version: "3"
services:
  headnode:
    build: headnode/
    image: centos
    command: python ./headnode/headnode.py
    networks:
      - app_net
    ports:
      - 5000:5000
      - 6000:6000
      - 7000:7000
      - 8000:8000
      - 10000:10000/udp
    volumes:
      - ./:/headnode/ 
    stdin_open: true
    tty: true
  datanode1:
    build: datanode1/
    command: python ./datanode1/datanode1.py
    networks:
      - app_net
    image: ubuntu
    depends_on:
      - headnode
    volumes:
      - ./:/datanode1/
    stdin_open: true
    tty: true
  datanode2:
    build: datanode2/
    command: python ./datanode2/datanode2.py
    networks:
      - app_net
    image: debian
    depends_on:
      - headnode
    volumes:
      - ./:/datanode2/
    stdin_open: true
    tty: true
  datanode3:
    build: datanode3/
    command: python ./datanode3/datanode3.py
    networks:
      - app_net
    depends_on:
      - headnode
    volumes:
      - ./:/datanode3/
    stdin_open: true
    tty: true
  client:
    build: client/
    command: python ./client/client.py
    networks:
      - app_net
    depends_on:
      - headnode
    volumes:
      - ./:/client/
    stdin_open: true
    tty: true
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"